apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: multus
  labels:
    app: busybox
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan-multus
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
